---
- name: customize_core_parameters
  hosts: all
  gather_facts: true
  become: true
  vars:
    grub_file: /etc/default/grub
    options:
      option1:
        name: net.ifnames
        val: 0
      option2:
        name: biosdevname
        val: 0

  tasks:
    - name: check if ifnames parameter is in GRUB_CMDLINE_LINUX line
      lineinfile:
        state: present
        path: "{{ grub_file }}"
        backrefs: true
#        ???????????????????????
#        regexp: '^(GRUB_CMDLINE_LINUX=".*{{ item.value.name }}.*)(")$'
        regexp: '^(GRUB_CMDLINE_LINUX=(?!.*{{ item.value.name }}) \"[^\"]+)(\".*)'
        line: '\1  {{ item.value.name }}={{ item.value.val }}\2'
      with_dict: "{{ options }}"
      notify: reload grub

  handlers:
    - name: reload grub
      shell: grub2-mkconfig
...
