---
- name: reload vsftpd
  systemd:
    name: vsftpd
    state: restarted
    enabled: yes

- name: reload firewalld
  service:
    name: firewalld
    state: reloaded

- name: apply SELinux
  command: restorecon -F -R -v /var/ftp/pub/
