---
- name: set facts
  set_fact:
    OS_Version: "{{ hostvars[inventory_hostname].ansible_distribution }}{{ hostvars[inventory_hostname].ansible_distribution_major_version }}"

- name: Say where we are at the moment
  debug:
    msg: "We are at {{ OS_Version }}"

## Install vsftpd service and other suitable packages
##
- name: Install vsftpd service and a package for SELinux module
  yum:
    name: "{{ item.value }}"
    state: present
  with_dict: "{{ packages[OS_Version] }}"

# create frp directories and set permissions
#
- name: create directory for anonimous access
  file:
    state: directory
    path: "{{ service_options.anonymous_dir }}"
    owner: nobody
    group: nobody
    mode: '0755'
  with_items: service_options

- name: create directory for uploads
  file:
    state: directory
    path: "{{ service_options.anonymous_upload_dir }}"
    owner: nobody
    group: nobody
    mode: '0777'
  with_items: service_options

## Configure vsftpd service with config template
##
- name: put vsftpd config file
  template:
    src: vsftpd.conf.j2
    dest: "{{ service_options.config_file }}"
    owner: root
    group: root
    mode: '0644'
  with_items: service_options
  notify: reload vsftpd

## Allow access to ftp
##
- name: Enable ftp service port
  firewalld:
    service: ftp
    permanent: yes
    state: enabled
  notify: reload firewalld

- name: Enable 21/tcp port
  firewalld:
    port: 21/tcp
    permanent: yes
    state: enabled
  notify: reload firewalld

- name: Enable 21/tcp port
  firewalld:
    port: 20/tcp
    permanent: yes
    state: enabled
  notify: reload firewalld

## Enable SELinux and allow ftp write anonimous policy
##
- name: Enable SELinux
  selinux:
    policy: targeted
    state: enforcing

- name: Set booleans for access anonimous ftp access
  seboolean:
    name: "{{ item }}"
    state: yes
    persistent: yes
  with_items: "{{ se_booleans }}"
  when:
    - ansible_selinux.status == "enabled"

- name: Allow ftp modify files in /var/ftp/pub/upload
  sefcontext:
    target: '/var/ftp/pub/upload(/.*)?'
    setype: public_content_rw_t
    state: present
  notify: apply SELinux
...